# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95e2d6ff1d7e61ade6e4618aca2fe134fcb18efc54f9a657bfd89f8a04e4c5a4dcd2c5b4fd2add0e80fe93d577ba0f21e26d8389a18c6196c8520a8d91c3ceee

test:
  secret_key_base: 6b290f19615c50a37734f8dd7244a5586565d55dfb43a5677962fa0929876c9892314fe8fc6fbe3b9be8105647338d28805d77484569f423acd186db98c250f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
